import { getInstance } from "../src/main"

getInstance().then(vm => {
    // Making a host variable that is used inside the VM
    window["hostVariable"] = "world!"

    // JavaScript that needs to be protected
    const code = vm.bytecode(`let a = "Hello " + host.run("window.hostVariable"); a;`);

    // Evaluating the generated bytecode;
    const result = vm.eval(code)

    // Getting "Hello world!" in the console.
    console.log(result)
})